Update chart from upstream
giantswarm/linkerd-control-plane-app pull request #151
Opened 2023-06-01 15:51 UTC by taylorbot

This PR was created by the `update-chart` automated workflow.

**:warning: Make sure all tests have passed before merging.**

2023-06-01 15:57 UTC, mcharriere requested changes

2023-06-01 15:57 UTC, mcharriere commented on helm/linkerd-control-plane/templates/heartbeat.yaml
> -              readOnlyRootFilesystem: true
not good

2023-06-01 15:57 UTC, mcharriere commented on helm/linkerd-control-plane/templates/destination.yaml
> -          readOnlyRootFilesystem: true
check

2023-06-01 15:57 UTC, mcharriere commented on helm/linkerd-control-plane/templates/destination.yaml
> -          readOnlyRootFilesystem: true
check

2023-06-08 13:08 UTC, Gacko approved these changes

2023-06-08 16:57 UTC, mcharriere approved these changes

2023-06-09 06:32 UTC, mcharriere approved these changes

2023-06-09 06:32 UTC, merged